### ISSUE TITLE
auto-indentation not working correctly for single line IF statements

### ISSUE THREAD

**Issue by schraf** [schraf/lowresnx-visualstudiocode-ext#1]
If you write a single line IF statement it will indent the next line after you press ENTER.

**Comment by rilden** [comment]
Created pull request https://github.com/schraf/lowresnx-visualstudiocode-ext/pull/5

Indent if:
 - line starts with SUB, ELSE, FOR, DO, REPEAT, WHILE
 - line is not a comment and ends with THEN

I think this should take care of all cases.
